apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: model-registry-token-reader
  namespace: rhoai-model
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["model-registry-token"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: model-registry-token-reader-pipeline-runner
  namespace: rhoai-model
subjects:
  - kind: ServiceAccount
    name: pipeline-runner-dspa
    namespace: rhoai-model
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: model-registry-token-reader
